export const profileData = [
    {
        id: 1,
        avatar: "https://www.jokesforfunny.com/wp-content/uploads/2021/06/0596bdb89b60fe771acd2f5972a9d3e3.jpg",
        username: "jack",
        info: "facebook",
    },
    {
        id: 2,
        avatar: "https://unqpost.com/wp-content/uploads/2020/11/Very-Funny-Profile-Pictures.jpg",
        username: "bob",
        info: "mcdonalds",
    },
    {
        id: 3,
        avatar: "https://pics.onsizzle.com/hey-i-steal-your-funny-profile-pics-admin-87-anime-49630925.png",
        username: "jill",
        info: "instagram",
    },
    {
        id: 4,
        avatar: "https://lh5.googleusercontent.com/proxy/MJkzkuzoHPUXY1bQ-F72GxaQtI5BKDYMxb35gGEj388-703VXDDOXfh8GRKr0e8S1MRm7LugT_8UL_pnn0egQE21_N7gsUNHEHPP4LTmHdX9EyUHmZdGPcXSRkOX6MdhT6iTskpcxTiDkg=w1200-h630-p-k-no-nu",
        username: "bill",
        info: "no where",
    },
    {
        id: 5,
        avatar: "https://i.pinimg.com/474x/ee/60/0b/ee600b5178e4f1648fd1e8623f049611.jpg",
        username: "skills",
        info: "gas station",
    },
    {
        id: 6,
        avatar: "https://pics.me.me/weiner-memes-weiner-memes4-instagram-profile-toopics-48909411.png",
        username: "papareact",
        info: "library",
    },
    {
        id: 7,
        avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWQaS0A9kM_NRDobEkMW7t6GXvKD2us3IjWA&usqp=CAU",
        username: "george",
        info: "new",
    },
    {
        id: 8,
        avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwZKwjbHe4E5DMnLBh4vp11EKugmDTz861Bw&usqp=CAU",
        username: "patrick",
        info: "new",
    },
    {
        id: 9,
        avatar: "https://i.pinimg.com/564x/67/0f/00/670f0086d7b533798b521ce559b9ea00.jpg",
        username: "herold",
        info: "new",
    },
    {
        id: 10,
        avatar: "https://d.newsweek.com/en/full/1920025/cat-its-mouth-open.jpg",
        username: "arty",
        info: "new",
    },
    {
        id: 11,
        avatar: "https://www.scarymommy.com/wp-content/uploads/2019/09/GettyImages-146582583-min-1.jpg",
        username: "carlos",
        info: "new",
    },
    {
        id: 12,
        avatar: "https://wl-brightside.cf.tsp.li/resize/728x/jpg/e54/e78/30a24451a8ba30d37a3dfa888c.jpg",
        username: "rudolf",
        info: "new",
    },
    {
        id: 13,
        avatar: "https://whatifgaming.com/wp-content/uploads/2021/10/9ede6016decdf83b9f16d4066750155c.jpg",
        username: "max",
        info: "jiffy-lube",
    },
    {
        id: 14,
        avatar: "https://whatifgaming.com/wp-content/uploads/2021/10/O9Wmyek.jpg",
        username: "buddy",
        info: "walmart",
    },
    {
        id: 15,
        avatar: "https://whatifgaming.com/wp-content/uploads/2021/10/JochaTara.jpg",
        username: "will",
        info: "target",
    },
    {
        id: 16,
        avatar: "https://whatifgaming.com/wp-content/uploads/2021/10/download-1-1.jpg",
        username: "sara",
        info: "cafe",
    },
    {
        id: 17,
        avatar: "https://i0.wp.com/pics.me.me/thumb_94-funny-chihuahua-face-chihuahuas-memes-funny-funny-memes-49077929.png",
        username: "lucky",
        info: "library",
    },
    {
        id: 18,
        avatar: "https://www.pinclipart.com/picdir/big/356-3564460_forgive-me-best-discord-profile-clipart.png",
        username: "charcol",
        info: "walmart",
    },
    {
        id: 19,
        avatar: "https://i.pinimg.com/236x/d4/73/c1/d473c12985d71e1253a993a8f31fcf70.jpg",
        username: "tree",
        info: "target",
    },
    {
        id: 20,
        avatar: "https://pfps.gg/assets/pfps/7113-trash-gang.png",
        username: "gas station",
        info: "gas",
    },
    {
        id: 21,
        avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD5KlktdWCSaVVTjkUwKYFvO1NtSNXnJRCnUVctMqPEKfbjra4Jrw42qydT3FYPaU4dCw&usqp=CAU",
        username: "cloud",
        info: "meta ",
    },
    {
        id: 22,
        avatar: "https://dthezntil550i.cloudfront.net/w0/latest/w01803170616133980003379724/1280_960/2e2d2647-6b1f-4177-b06c-9b2288aeb455.png",
        username: "user213",
        info: "new",
    },
    
]