import Head from 'next/head'
import Header from '../components/Header';
import Feed from '../components/Feed'




function Home() {

  

  return (

    <div className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>Instagram Clone </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>

      
      <Header />
      <Feed />


      </div>

    </div>

  )

}

export default Home;